language: node_js
sudo: false

node_js:
  - 6

install:
  # Install packages.
  - npm install

before_script:
  # Need Gulp ro trigger the analysis on SonarQube.com
  - npm install -g gulp

script:
  # Actually calls Gulp - the SonarQube analysis is the default task
  - gulp

cache:
  directories:
    - $HOME/.npm
    - $HOME/.sonar/cache
    - $HOME/.sonar/native-sonar-scanner
